[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "chefshatgym"
authors = [{name = "Pablo Barros", email = "pablovin@gmail.com"}]
dynamic = ["version", "description"]